# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20180703_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='manage_mc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=150, verbose_name='hostname')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company_admin', verbose_name='公司')),
            ],
            options={
                'db_table': 'manage_mc',
            },
        ),
    ]
