# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_setting', '0003_manage_mc_line'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manage_mc',
            new_name='mc_manage',
        ),
    ]
