# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_setting', '0004_auto_20180706_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mc_manage',
            new_name='machine_manage',
        ),
    ]
