# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_setting', '0005_auto_20180706_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_manage',
            name='disk_limit',
            field=models.FloatField(default=10, max_length=4, verbose_name='disk_limit'),
        ),
    ]
