# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_setting', '0007_machine_manage_disk_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_manage',
            name='report_time',
            field=models.DateField(default=datetime.datetime(2018, 7, 24, 15, 45, 15, 784716), verbose_name='Make Report Time'),
        ),
        migrations.AlterField(
            model_name='machine_manage',
            name='disk_limit',
            field=models.FloatField(default=10, max_length=4, verbose_name='disk_limit(GB)'),
        ),
        migrations.AlterField(
            model_name='machine_manage',
            name='disk_percent',
            field=models.BooleanField(default=1, verbose_name='Disk Use Percentage'),
        ),
    ]
