# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_setting', '0008_auto_20180724_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_manage',
            name='report_time',
            field=models.TimeField(default=datetime.datetime(2018, 7, 24, 15, 46, 10, 135850), verbose_name='Make Report Time'),
        ),
    ]
