# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=6, verbose_name='暫時密碼')),
                ('expiration', models.DateField(blank=True, verbose_name='有效日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '暫時密碼',
                'verbose_name_plural': '使用者暫時密碼',
                'db_table': 'Temp_Pass',
            },
        ),
        migrations.AlterField(
            model_name='company_admin',
            name='company_ip2',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='公司IP位址2'),
        ),
        migrations.AlterField(
            model_name='company_admin',
            name='company_ip3',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='公司IP位址3'),
        ),
        migrations.AlterField(
            model_name='company_admin',
            name='date_expiration',
            field=models.DateField(blank=True, verbose_name='有效日期'),
        ),
    ]
