# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180703_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_pass',
            name='temp',
            field=models.CharField(max_length=6, unique=True, verbose_name='暫時密碼'),
        ),
    ]
