# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180703_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_admin',
            name='company_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='公司統編'),
        ),
    ]
